// @humanwrites/api-client - Auto-generated by orval from OpenAPI schema
// DO NOT manually edit files in src/generated/
export { axiosInstance, customInstance } from './axios-instance';

// Re-export generated types and hooks when available
// export * from './generated/endpoints';
// export * from './generated/models';
